"""Models package."""

from app.models.database import (
    Base,
    Podcast,
    Transcript,
    Insight,
    Chunk,
    Conversation,
    Message,
    Job,
    engine,
    SessionLocal,
    init_db,
    get_db,
)
from app.models.schemas import (
    PodcastCreate,
    PodcastResponse,
    PodcastCreateResponse,
    PodcastListResponse,
    PodcastDetailResponse,
    TranscriptResponse,
    TranscriptSegment,
    ChunkResponse,
    SearchRequest,
    SearchResult,
    SearchResponse,
    JobResponse,
    InsightResponse,
    ChatRequest,
    ChatResponse,
    ChatMessageResponse,
    SourceCitation,
    ConversationResponse,
    ConversationListResponse,
)

__all__ = [
    # Database models
    "Base",
    "Podcast",
    "Transcript",
    "Insight",
    "Chunk",
    "Conversation",
    "Message",
    "Job",
    "engine",
    "SessionLocal",
    "init_db",
    "get_db",
    # Schemas
    "PodcastCreate",
    "PodcastResponse",
    "PodcastCreateResponse",
    "PodcastListResponse",
    "PodcastDetailResponse",
    "TranscriptResponse",
    "TranscriptSegment",
    "ChunkResponse",
    "SearchRequest",
    "SearchResult",
    "SearchResponse",
    "JobResponse",
    "InsightResponse",
    "ChatRequest",
    "ChatResponse",
    "ChatMessageResponse",
    "SourceCitation",
    "ConversationResponse",
    "ConversationListResponse",
]
