export default function PrivacyPolicy() {
  return (
    <div className="h-full overflow-y-auto">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-2xl font-semibold tracking-tight mb-1">Privacy Policy</h1>
        <p className="text-[13px] mute mb-8">
          Effective Date: May 24, 2026 &middot; Last Updated: May 24, 2026
        </p>

        <div className="space-y-8 text-[14px] leading-relaxed dim">
          <p>
            PodBrain is operated by Nick Lasky, an individual based in the United States.
            This Privacy Policy explains what data PodBrain collects, why we collect it,
            how we share it, and what rights you have over it.
          </p>
          <p>
            If you have questions, contact us at{' '}
            <a href="mailto:nl.nicklasky@gmail.com" className="text-[var(--accent)] hover:underline">
              nl.nicklasky@gmail.com
            </a>.
          </p>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">1. What We Collect</h2>
            <p className="mb-3">We collect data in two categories: data you provide and data generated by our system.</p>

            <h3 className="text-[14px] font-semibold text-[var(--text)] mb-2">Data you provide directly:</h3>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li><strong>Knowledge base content</strong> — names, descriptions, and organization of your knowledge bases.</li>
              <li><strong>Podcast selections</strong> — URLs, titles, and show names of podcasts you add.</li>
              <li><strong>Chat messages</strong> — questions you ask within knowledge base conversations.</li>
              <li><strong>Search queries</strong> — text you enter when searching across podcast content.</li>
            </ul>

            <h3 className="text-[14px] font-semibold text-[var(--text)] mb-2">Data our system generates from your input:</h3>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li><strong>Transcripts</strong> — full text and timestamped segments produced by transcribing podcast audio.</li>
              <li><strong>Text chunks and embeddings</strong> — segments of transcript text and their mathematical vector representations, used for search.</li>
              <li><strong>AI-generated insights</strong> — summaries, topic lists, key points, and named entities extracted from transcripts.</li>
              <li><strong>Chat responses</strong> — AI-generated answers with source citations from your podcast library.</li>
              <li><strong>Processing logs</strong> — technical records of pipeline steps (downloading, transcribing, embedding).</li>
            </ul>

            <h3 className="text-[14px] font-semibold text-[var(--text)] mb-2">Data collected automatically:</h3>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li><strong>IP addresses</strong> — collected by our hosting providers (Vercel, Supabase) through standard web server logs.</li>
            </ul>

            <p>
              We do not collect names, email addresses, or payment information at this time.
              When we add user accounts, we will update this policy to cover authentication data.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">2. How We Use Your Data</h2>
            <div className="overflow-x-auto mb-3">
              <table className="w-full text-[13px] border-collapse">
                <thead>
                  <tr className="border-b border-[var(--border)]">
                    <th className="text-left py-2 pr-4 font-semibold text-[var(--text)]">Purpose</th>
                    <th className="text-left py-2 font-semibold text-[var(--text)]">Lawful Basis (GDPR)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[var(--border-soft)]">
                  <tr>
                    <td className="py-2 pr-4">Providing the core service (knowledge bases, transcription, search, chat)</td>
                    <td className="py-2">Performance of contract (Art. 6(1)(b)) / Consent</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">Generating AI insights and embeddings from podcast content</td>
                    <td className="py-2">Performance of contract (Art. 6(1)(b))</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">Improving service reliability via processing logs</td>
                    <td className="py-2">Legitimate interest (Art. 6(1)(f))</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">Responding to your support requests</td>
                    <td className="py-2">Legitimate interest (Art. 6(1)(f))</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p>We do <strong>not</strong> use your data for advertising, profiling, or automated decision-making that produces legal effects.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">3. Third-Party Data Processors</h2>
            <p className="mb-3">
              We share data with the following service providers, solely to operate PodBrain.
              Each processes data on our behalf and under our instructions.
            </p>
            <div className="overflow-x-auto mb-3">
              <table className="w-full text-[13px] border-collapse">
                <thead>
                  <tr className="border-b border-[var(--border)]">
                    <th className="text-left py-2 pr-4 font-semibold text-[var(--text)]">Provider</th>
                    <th className="text-left py-2 pr-4 font-semibold text-[var(--text)]">Data Shared</th>
                    <th className="text-left py-2 pr-4 font-semibold text-[var(--text)]">Purpose</th>
                    <th className="text-left py-2 font-semibold text-[var(--text)]">Location</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[var(--border-soft)]">
                  <tr>
                    <td className="py-2 pr-4 font-medium text-[var(--text)]">OpenAI</td>
                    <td className="py-2 pr-4">Transcript text (chunks), chat queries, audio files</td>
                    <td className="py-2 pr-4">Transcription (Whisper), embeddings, insight generation, chat responses</td>
                    <td className="py-2">USA</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 font-medium text-[var(--text)]">Groq</td>
                    <td className="py-2 pr-4">Audio files, transcript text</td>
                    <td className="py-2 pr-4">Alternative audio transcription and AI processing</td>
                    <td className="py-2">USA</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 font-medium text-[var(--text)]">Supabase</td>
                    <td className="py-2 pr-4">All application data</td>
                    <td className="py-2 pr-4">Database hosting, file storage, edge function compute</td>
                    <td className="py-2">USA</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 font-medium text-[var(--text)]">Vercel</td>
                    <td className="py-2 pr-4">IP addresses, request metadata</td>
                    <td className="py-2 pr-4">Web application hosting and delivery</td>
                    <td className="py-2">USA</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4 font-medium text-[var(--text)]">Podcast Index</td>
                    <td className="py-2 pr-4">Search query strings</td>
                    <td className="py-2 pr-4">Podcast discovery API</td>
                    <td className="py-2">USA</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="mb-2">
              We require Data Processing Agreements (DPAs) from each processor. OpenAI's DPA is available at{' '}
              <a href="https://openai.com/policies/data-processing-addendum/" className="text-[var(--accent)] hover:underline" target="_blank" rel="noopener noreferrer">
                openai.com/policies/data-processing-addendum
              </a>.
            </p>
            <p className="mb-2">
              <strong>International transfers:</strong> All processors are based in the United States.
              For users in the European Economic Area (EEA), UK, or Switzerland, we rely on Standard
              Contractual Clauses (SCCs) as adopted by the European Commission to safeguard transfers
              under GDPR Articles 44-49.
            </p>
            <p>We do <strong>not</strong> sell your personal data to any third party.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">4. Data Retention</h2>
            <div className="overflow-x-auto mb-3">
              <table className="w-full text-[13px] border-collapse">
                <thead>
                  <tr className="border-b border-[var(--border)]">
                    <th className="text-left py-2 pr-4 font-semibold text-[var(--text)]">Data Type</th>
                    <th className="text-left py-2 font-semibold text-[var(--text)]">Retention Period</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[var(--border-soft)]">
                  <tr>
                    <td className="py-2 pr-4">Knowledge bases, podcasts, transcripts, chunks, insights</td>
                    <td className="py-2">Retained while your account is active; deleted upon request</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">Chat conversations and messages</td>
                    <td className="py-2">Retained while your account is active; deleted upon request</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">Search history</td>
                    <td className="py-2">90 days, then automatically purged</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">Processing logs</td>
                    <td className="py-2">30 days, then automatically purged</td>
                  </tr>
                  <tr>
                    <td className="py-2 pr-4">Audio files</td>
                    <td className="py-2">Deleted immediately after transcription is complete</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p>
              When you delete a knowledge base or podcast through the app, associated transcripts,
              chunks, insights, and conversations are permanently deleted via cascading deletion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">5. Your Rights</h2>

            <h3 className="text-[14px] font-semibold text-[var(--text)] mb-2">For all users</h3>
            <p className="mb-2">You may request to:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li><strong>Access</strong> your data — receive a copy of the personal data we hold about you.</li>
              <li><strong>Delete</strong> your data — request permanent deletion of your account and all associated data.</li>
              <li><strong>Export</strong> your data — receive your data in a portable, machine-readable format.</li>
            </ul>

            <h3 className="text-[14px] font-semibold text-[var(--text)] mb-2">Additional rights under GDPR (EEA, UK, Swiss residents)</h3>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li><strong>Rectification</strong> — correct inaccurate personal data.</li>
              <li><strong>Restriction</strong> — limit how we process your data in certain circumstances.</li>
              <li><strong>Object</strong> — object to processing based on legitimate interest.</li>
              <li><strong>Withdraw consent</strong> — where processing is based on consent, withdraw it at any time without affecting prior processing.</li>
              <li><strong>Lodge a complaint</strong> with your local Data Protection Authority.</li>
            </ul>

            <h3 className="text-[14px] font-semibold text-[var(--text)] mb-2">Additional rights under CCPA (California residents)</h3>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li><strong>Right to Know</strong> — request disclosure of the categories and specific pieces of personal information we have collected.</li>
              <li><strong>Right to Delete</strong> — request deletion of personal information we have collected from you.</li>
              <li><strong>Right to Opt-Out of Sale/Sharing</strong> — we do not sell or share your personal information as defined by the CCPA.</li>
              <li><strong>Non-Discrimination</strong> — we will not discriminate against you for exercising your CCPA rights.</li>
            </ul>

            <p>
              To exercise any of these rights, email{' '}
              <a href="mailto:nl.nicklasky@gmail.com" className="text-[var(--accent)] hover:underline">
                nl.nicklasky@gmail.com
              </a>.
              We will respond within 30 days (GDPR) or 45 days (CCPA).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">6. Security</h2>
            <p className="mb-3">We implement the following measures to protect your data:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>All data transmitted between your browser and our servers is encrypted via TLS (HTTPS).</li>
              <li>Database access is restricted through Supabase Row Level Security (RLS) policies.</li>
              <li>API keys for third-party services (OpenAI, Groq, Podcast Index) are stored as server-side secrets and are never exposed to the browser.</li>
              <li>Audio files are deleted from storage immediately after transcription completes.</li>
              <li>Edge Function endpoints are restricted to authorized origins via CORS policies.</li>
            </ul>
            <p>
              No system is perfectly secure. If we discover a data breach that affects your personal data,
              we will notify you and any applicable regulatory authority as required by law.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">7. Children's Privacy</h2>
            <p>
              PodBrain is not directed at children under 16 (or under 13 in the United States).
              We do not knowingly collect personal data from children. If you believe a child has provided
              us with personal data, contact us at{' '}
              <a href="mailto:nl.nicklasky@gmail.com" className="text-[var(--accent)] hover:underline">
                nl.nicklasky@gmail.com
              </a>{' '}
              and we will delete it promptly.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">8. Changes to This Policy</h2>
            <p className="mb-2">We may update this Privacy Policy from time to time. When we make material changes, we will:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>Update the "Last Updated" date at the top of this page.</li>
              <li>Notify active users via email or an in-app notice before the changes take effect.</li>
            </ul>
            <p>Your continued use of PodBrain after changes are posted constitutes acceptance of the updated policy.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--text)] mb-3">9. Contact</h2>
            <p className="mb-2">For any privacy-related questions, data requests, or complaints:</p>
            <p>
              <strong className="text-[var(--text)]">Nick Lasky</strong><br />
              Email:{' '}
              <a href="mailto:nl.nicklasky@gmail.com" className="text-[var(--accent)] hover:underline">
                nl.nicklasky@gmail.com
              </a>
            </p>
            <p className="mt-2">
              If you are in the EEA and are not satisfied with our response, you have the right to
              lodge a complaint with your local Data Protection Authority.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
